version: '3.9'
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/project.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    networks:
      - default
  webapp:
    build: ./docker/php
    image: myapp:symfony
    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - default
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a1b2c3
      MYSQL_DATABASE: myapp
    ports:
      - '33061:3306'
    volumes:
      - mysql-datavolume3:/var/lib/mysql
    networks:
      - default
  node:
    build: ./docker/node
    image: myapp:node
    volumes:
      - ./:/app
    ports:
      - '4200:4200'
    command: npm run dev:ssr
    networks:
      - default
volumes:
  mysql-datavolume3:
